### ISSUE TITLE
can not set the callback url

### ISSUE THREAD

**Issue by paulovitorbal** [Jorijn/symfony-bunq-bundle#1]
Yesterday I was trying to create a new integration and I could not set the callback url through the `bunq:callback-url`. I will try to fix this up in my free time and then send a PR.

I don't have the exception right now, but it says something related to a `cards` field.

**Comment by jorijn** [comment]
Hey @paulovitorbal, 

Thanks for reporting. They did change some things about their API since I initially developed this package. I'll be looking forward to your PR.

**Comment by jorijn** [comment]
Fixed in v1.0.1
